version: "3"
services: 
  redis:
    image: redis
    container_name: pangaea_redis
    networks:
      - webnet
    volumes:
      - redis-data:/var/lib/redis/data
    command: "redis-server"
  mongodb:
    image: mongo
    container_name: pangaea_mongodb
    networks:
      - webnet
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo-data:/var/lib/mongodb/data
    ports: 
      - 27017:27017

networks:
  webnet:
volumes:
  mongo-data:
  redis-data: